import React, { useState, useEffect } from 'react';
import { Navigation } from './components/Navigation';
import { Home } from './components/Home';
import { Dashboard } from './components/Dashboard';
import { ToolLayout } from './components/tools/ToolLayout';
import { MindMapView } from './components/tools/MindMap';
import { QuizView } from './components/tools/Quiz';
import { FlashcardView } from './components/tools/Flashcards';
import { TutorChat } from './components/tools/TutorChat';
import { TextbookView } from './components/tools/Textbook';
import { SubjectSelector } from './components/SubjectSelector';
import { UnitSelector } from './components/UnitSelector';
import { LanguageAddon } from './components/LanguageAddon';
import { CloudLibrary } from './components/CloudLibrary';
import { GitHubExportModal } from './components/GitHubExportModal';
import { 
  generateMindMap, 
  generateQuiz, 
  generateFlashcards, 
  generateTextbook,
  MindMapNode, 
  QuizQuestion, 
  Flashcard 
} from './services/gemini';
import { 
  saveMindMapToFirebase, 
  saveQuizToFirebase, 
  saveFlashcardsToFirebase, 
  saveTextbookToFirebase,
  getCachedMindMap,
  getCachedQuiz,
  getCachedFlashcards,
  getCachedTextbook,
  seedAllPreGeneratedDataToFirebase
} from './services/firebaseStudyService';
import { initAuth } from './lib/firebase';
import { AnimatePresence, motion } from 'motion/react';
import { Cloud, CheckCircle2, Database, Zap } from 'lucide-react';

type ViewState = 'landing' | 'subject' | 'language' | 'unit' | 'dashboard' | 'mindmap' | 'quiz' | 'flashcards' | 'textbook' | 'tutor';

export default function App() {
  const [view, setView] = useState<ViewState>('landing');
  const [level, setLevel] = useState<string>('Form 1');
  const [language, setLanguage] = useState<string>('BM + English');
  const [subject, setSubject] = useState<string | null>(null);
  const [unit, setUnit] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isCloudLibraryOpen, setIsCloudLibraryOpen] = useState(false);
  const [isGitHubModalOpen, setIsGitHubModalOpen] = useState(false);
  const [cloudNotification, setCloudNotification] = useState<string | null>(null);
  const [isCachedTool, setIsCachedTool] = useState(false);
  
  // Data states
  const [mindMapData, setMindMapData] = useState<MindMapNode | null>(null);
  const [quizData, setQuizData] = useState<QuizQuestion[] | null>(null);
  const [flashcardData, setFlashcardData] = useState<Flashcard[] | null>(null);
  const [textbookContent, setTextbookContent] = useState<string | null>(null);

  // Track units that have already attempted auto-generation to prevent infinite loops
  const autoGeneratedUnitsRef = React.useRef<Set<string>>(new Set());

  // Initialize Firebase Auth and pre-warm cache on app mount
  useEffect(() => {
    initAuth().catch(err => console.warn('Auth init failed:', err));
    // Pre-cache standard Form 1 syllabus so Firebase is populated without needing continuous AI
    seedAllPreGeneratedDataToFirebase().then(res => {
      if (res.unitsCount > 0) {
        console.log(`[Firebase Cache] ${res.unitsCount} Form 1 syllabus packs ready in Firestore.`);
      }
    }).catch(err => console.warn('Auto-seed background check:', err));
  }, []);

  const showNotification = (msg: string) => {
    setCloudNotification(msg);
    setTimeout(() => {
      setCloudNotification(null);
    }, 4500);
  };

  const handleSelectLevel = (l: string = 'Form 1') => {
    setLevel('Form 1');
    setView('subject');
  };

  const handleSelectSubject = (sub: string) => {
    setSubject(sub);
    setLevel('Form 1');
    
    // Auto-language mapping (Textbook defaults)
    let defaultLang = 'BM + English';
    const subLower = sub.toLowerCase();
    if (subLower.includes('science') || subLower.includes('math')) {
      defaultLang = 'English';
    } else if (subLower.includes('chinese') || subLower.includes('mandarin')) {
      defaultLang = 'Chinese';
    } else if (subLower.includes('melayu')) {
      defaultLang = 'Bahasa Melayu';
    }
    
    setLanguage(defaultLang);
    setView('language');
  };

  const handleSelectLanguage = (lang: string) => {
    setLanguage(lang);
    setView('unit');
  };

  const handleSelectUnit = (u: string) => {
    setUnit(u);
    setView('dashboard');
  };

  // Auto-check and load tools safely once per unit when entering view
  useEffect(() => {
    if (!unit || isLoading) return;

    if (view === 'mindmap' && !mindMapData) {
      if (!autoGeneratedUnitsRef.current.has(`mindmap-${unit}`)) {
        autoGeneratedUnitsRef.current.add(`mindmap-${unit}`);
        handleGenerateMindMap(unit, undefined, false);
      }
    } else if (view === 'quiz' && !quizData) {
      if (!autoGeneratedUnitsRef.current.has(`quiz-${unit}`)) {
        autoGeneratedUnitsRef.current.add(`quiz-${unit}`);
        handleGenerateQuiz(unit, undefined, false);
      }
    } else if (view === 'flashcards' && !flashcardData) {
      if (!autoGeneratedUnitsRef.current.has(`flashcards-${unit}`)) {
        autoGeneratedUnitsRef.current.add(`flashcards-${unit}`);
        handleGenerateFlashcards(unit, undefined, false);
      }
    } else if (view === 'textbook' && !textbookContent) {
      if (!autoGeneratedUnitsRef.current.has(`textbook-${unit}`)) {
        autoGeneratedUnitsRef.current.add(`textbook-${unit}`);
        handleGenerateTextbook(false);
      }
    }
  }, [view, unit, mindMapData, quizData, flashcardData, textbookContent, isLoading]);

  const handleBack = () => {
    if (view === 'dashboard') {
      setView('unit');
    } else if (view === 'unit') {
      setView('language');
    } else if (view === 'language') {
      setView('subject');
    } else if (view === 'subject') {
      setView('landing');
    } else if (view === 'landing') {
      // already at home
    } else {
      setView('dashboard');
      // Reset tool data
      setMindMapData(null);
      setQuizData(null);
      setFlashcardData(null);
      setTextbookContent(null);
      setIsCachedTool(false);
    }
  };

  const handleGenerateMindMap = async (topic: string, customLang?: string, forceAI = false) => {
    setIsLoading(true);
    try {
      const selectedLang = customLang || language;
      const targetUnit = unit || topic;

      // 1. Check Firebase cache first unless forced
      if (!forceAI) {
        const cached = await getCachedMindMap('Form 1', subject || '', targetUnit);
        if (cached && cached.id !== 'error') {
          setMindMapData(cached);
          setIsCachedTool(true);
          showNotification(`⚡ Loaded Mindmap "${topic}" from Firebase Cloud Cache (0 AI quota used)`);
          return;
        }
      }

      // 2. Generate with Gemini AI
      const data = await generateMindMap(topic, 'Form 1', subject || '', selectedLang);
      setMindMapData(data);
      setIsCachedTool(false);
      if (data && data.id !== 'error') {
        await saveMindMapToFirebase(topic, 'Form 1', subject || '', targetUnit, selectedLang, data);
        showNotification(`Mindmap "${topic}" saved to Firebase backend!`);
      } else {
        showNotification(`Generated mindmap for "${topic}"`);
      }
    } catch (err) {
      console.error(err);
      showNotification("Could not complete mindmap generation. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerateQuiz = async (topic: string, customLang?: string, forceAI = false) => {
    setIsLoading(true);
    try {
      const selectedLang = customLang || language;
      const targetUnit = unit || topic;

      // 1. Check Firebase cache first unless forced
      if (!forceAI) {
        const cached = await getCachedQuiz('Form 1', subject || '', targetUnit);
        if (cached && cached.length > 0) {
          setQuizData(cached);
          setIsCachedTool(true);
          showNotification(`⚡ Loaded Quiz "${topic}" from Firebase Cloud Cache (0 AI quota used)`);
          return;
        }
      }

      // 2. Generate with Gemini AI
      const data = await generateQuiz(topic, 'Form 1', subject || '', selectedLang);
      setQuizData(data);
      setIsCachedTool(false);
      if (data && data.length > 0) {
        await saveQuizToFirebase(topic, 'Form 1', subject || '', targetUnit, selectedLang, data);
        showNotification(`Quiz for "${topic}" saved to Firebase backend!`);
      }
    } catch (err) {
      console.error(err);
      showNotification("Could not complete quiz generation. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerateFlashcards = async (topic: string, customLang?: string, forceAI = false) => {
    setIsLoading(true);
    try {
      const selectedLang = customLang || language;
      const targetUnit = unit || topic;

      // 1. Check Firebase cache first unless forced
      if (!forceAI) {
        const cached = await getCachedFlashcards('Form 1', subject || '', targetUnit);
        if (cached && cached.length > 0) {
          setFlashcardData(cached);
          setIsCachedTool(true);
          showNotification(`⚡ Loaded Flashcards "${topic}" from Firebase Cloud Cache (0 AI quota used)`);
          return;
        }
      }

      // 2. Generate with Gemini AI
      const data = await generateFlashcards(topic, 'Form 1', subject || '', selectedLang);
      setFlashcardData(data);
      setIsCachedTool(false);
      if (data && data.length > 0) {
        await saveFlashcardsToFirebase(topic, 'Form 1', subject || '', targetUnit, selectedLang, data);
        showNotification(`Flashcard deck for "${topic}" saved to Firebase backend!`);
      }
    } catch (err) {
      console.error(err);
      showNotification("Could not complete flashcard generation. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerateTextbook = async (forceAI = false) => {
    setIsLoading(true);
    try {
      const currentUnit = unit || 'Syllabus';

      // 1. Check Firebase cache first unless forced
      if (!forceAI) {
        const cached = await getCachedTextbook('Form 1', subject || '', currentUnit);
        if (cached && cached.trim()) {
          setTextbookContent(cached);
          setIsCachedTool(true);
          showNotification(`⚡ Loaded Textbook for "${currentUnit}" from Firebase Cloud Cache (0 AI quota used)`);
          return;
        }
      }

      // 2. Generate with Gemini AI
      const data = await generateTextbook(currentUnit, 'Form 1', subject || '', language);
      setTextbookContent(data);
      setIsCachedTool(false);
      if (data && data.trim()) {
        await saveTextbookToFirebase(currentUnit, 'Form 1', subject || '', language, data);
        showNotification(`Textbook for "${currentUnit}" saved to Firebase backend!`);
      }
    } catch (err) {
      console.error(err);
      showNotification("Could not complete textbook summary. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  // Load from Firebase Cloud storage
  const handleLoadSavedMindMap = (data: MindMapNode, topic: string, l: string, s: string, u: string) => {
    if (l) setLevel(l);
    if (s) setSubject(s);
    if (u) setUnit(u);
    setMindMapData(data);
    setView('mindmap');
    showNotification(`Loaded Mindmap "${topic}" from Firebase`);
  };

  const handleLoadSavedQuiz = (questions: QuizQuestion[], topic: string, l: string, s: string, u: string) => {
    if (l) setLevel(l);
    if (s) setSubject(s);
    if (u) setUnit(u);
    setQuizData(questions);
    setView('quiz');
    showNotification(`Loaded Quiz "${topic}" from Firebase`);
  };

  const handleLoadSavedFlashcards = (cards: Flashcard[], topic: string, l: string, s: string, u: string) => {
    if (l) setLevel(l);
    if (s) setSubject(s);
    if (u) setUnit(u);
    setFlashcardData(cards);
    setView('flashcards');
    showNotification(`Loaded Flashcards "${topic}" from Firebase`);
  };

  const handleLoadSavedTextbook = (content: string, u: string, l: string, s: string) => {
    if (l) setLevel(l);
    if (s) setSubject(s);
    if (u) setUnit(u);
    setTextbookContent(content);
    setView('textbook');
    showNotification(`Loaded Textbook "${u}" from Firebase`);
  };

  return (
    <div className="min-h-screen bg-[#02000D] text-[#EBDED4] relative overflow-x-hidden">
      {/* Background Atmosphere Orbs */}
      <div className="fixed top-0 left-0 w-full h-full pointer-events-none overflow-hidden">
        <div className="absolute top-[-10%] right-[-10%] w-[55%] h-[55%] bg-[#07203F]/60 blur-[130px] rounded-full" />
        <div className="absolute bottom-[-10%] left-[-10%] w-[50%] h-[50%] bg-[#A65E46]/20 blur-[140px] rounded-full" />
        <div className="absolute top-[40%] left-[30%] w-[35%] h-[35%] bg-[#D9AA90]/10 blur-[150px] rounded-full" />
      </div>

      <Navigation 
        currentLevel={view === 'landing' ? null : 'Form 1'} 
        onBack={handleBack} 
        title={view === 'landing' ? 'Welcome • Form 1' : `Form 1 • ${subject || 'Select Subject'}`}
        onOpenCloudLibrary={() => setIsCloudLibraryOpen(true)}
        onOpenGitHubModal={() => setIsGitHubModalOpen(true)}
      />

      {/* Cloud Notification Toast */}
      <AnimatePresence>
        {cloudNotification && (
          <motion.div
            initial={{ opacity: 0, y: -20, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: -20, scale: 0.95 }}
            className="fixed top-20 right-6 z-50 glass-card px-4 py-3 rounded-2xl border border-[#D9AA90]/40 shadow-xl shadow-[#A65E46]/10 flex items-center gap-3 bg-[#02000D]/95 text-[#EBDED4]"
          >
            <div className="w-8 h-8 rounded-full bg-[#A65E46]/20 flex items-center justify-center text-[#D9AA90]">
              <Cloud size={16} />
            </div>
            <div className="text-xs">
              <div className="font-bold text-[#D9AA90] flex items-center gap-1">
                <CheckCircle2 size={12} /> Firebase Backend Saved
              </div>
              <div className="text-[#EBDED4]/80">{cloudNotification}</div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Cloud Library Modal */}
      <CloudLibrary
        isOpen={isCloudLibraryOpen}
        onClose={() => setIsCloudLibraryOpen(false)}
        onLoadMindMap={handleLoadSavedMindMap}
        onLoadQuiz={handleLoadSavedQuiz}
        onLoadFlashcards={handleLoadSavedFlashcards}
        onLoadTextbook={handleLoadSavedTextbook}
      />

      {/* GitHub Export Modal */}
      <GitHubExportModal
        isOpen={isGitHubModalOpen}
        onClose={() => setIsGitHubModalOpen(false)}
      />

      <AnimatePresence mode="wait">
        <main className="relative z-10 min-h-[70vh]">
          {view === 'landing' && (
            <motion.div key="landing" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <Home onSelectLevel={handleSelectLevel} onQuickSelectSubject={handleSelectSubject} />
            </motion.div>
          )}

          {view === 'subject' && (
            <motion.div key="subject" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <SubjectSelector onSelect={handleSelectSubject} level={level || ''} />
            </motion.div>
          )}

          {view === 'language' && (
            <motion.div key="language" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <LanguageAddon 
                subject={subject || ''} 
                defaultLang={language} 
                onSelect={handleSelectLanguage} 
              />
            </motion.div>
          )}

          {view === 'unit' && (
            <motion.div key="unit" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <UnitSelector 
                level={level || ''} 
                subject={subject || ''} 
                language={language || ''} 
                onSelect={handleSelectUnit} 
              />
            </motion.div>
          )}

          {view === 'dashboard' && (
            <motion.div key="dashboard" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <Dashboard 
                level={level || ''}
                subject={subject || ''}
                unit={unit}
                onSelectTool={(tool) => setView(tool as ViewState)}
                onChangeUnit={() => setView('unit')}
                onOpenCloudLibrary={() => setIsCloudLibraryOpen(true)}
              />
            </motion.div>
          )}

          {view === 'mindmap' && (
            <motion.div key="mindmap" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <ToolLayout 
                title={`${subject} Mindmap`} 
                description={`Visualizing Unit: ${unit} • Stored in Firebase`}
                isLoading={isLoading}
                onGenerate={(t, lang, force) => handleGenerateMindMap(t, lang, force)}
                defaultTopic={unit || ''}
                isCached={isCachedTool}
                onRegenerateAI={() => handleGenerateMindMap(unit || subject || 'Overview', undefined, true)}
              >
                {mindMapData && (
                  <MindMapView 
                    node={mindMapData} 
                    onRetry={() => handleGenerateMindMap(unit || subject || 'Overview', undefined, true)}
                  />
                )}
              </ToolLayout>
            </motion.div>
          )}

          {view === 'quiz' && (
            <motion.div key="quiz" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <ToolLayout 
                title={`${subject} Smart Quiz`} 
                description={`Generating MCQs for ${unit} • Stored in Firebase`}
                isLoading={isLoading}
                onGenerate={(t, lang, force) => handleGenerateQuiz(t, lang, force)}
                defaultTopic={unit || ''}
                isCached={isCachedTool}
                onRegenerateAI={() => handleGenerateQuiz(unit || subject || 'Quiz', undefined, true)}
              >
                {quizData && <QuizView questions={quizData} onReset={() => setQuizData(null)} />}
              </ToolLayout>
            </motion.div>
          )}

          {view === 'flashcards' && (
            <motion.div key="flashcards" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <ToolLayout 
                title={`${subject} Flashcards`} 
                description={`Cards for ${unit} • Stored in Firebase`}
                isLoading={isLoading}
                onGenerate={(t, lang, force) => handleGenerateFlashcards(t, lang, force)}
                defaultTopic={unit || ''}
                isCached={isCachedTool}
                onRegenerateAI={() => handleGenerateFlashcards(unit || subject || 'Cards', undefined, true)}
              >
                {flashcardData && <FlashcardView cards={flashcardData} />}
              </ToolLayout>
            </motion.div>
          )}

          {view === 'textbook' && (
            <motion.div key="textbook" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="pt-32 pb-20 px-6">
              <TextbookView 
                unit={unit || ''}
                content={textbookContent}
                isLoading={isLoading}
                onGenerate={() => handleGenerateTextbook(false)}
                onRegenerateAI={() => handleGenerateTextbook(true)}
                isCached={isCachedTool}
              />
            </motion.div>
          )}

          {view === 'tutor' && (
            <motion.div key="tutor" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="pt-32 pb-20 px-6">
              <TutorChat 
                level={level || ''} 
                subject={subject || ''} 
                language={language || ''} 
                unit={unit}
              />
            </motion.div>
          )}
        </main>
      </AnimatePresence>

      <footer className="py-12 border-t border-[#D9AA90]/15 relative z-10 bg-[#02000D]/80 backdrop-blur-md">
        <div className="max-w-6xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-2">
            <span className="font-display font-bold text-sm tracking-widest uppercase text-[#EBDED4]">
              STUDY<span className="text-[#A65E46]">LAH</span>
            </span>
          </div>
          <p className="text-[#EBDED4]/40 text-xs text-center md:text-left">
            Built for Malaysian Secondary Schools. All AI outputs are generated and saved to Firebase Firestore backend.
          </p>
          <div className="flex items-center gap-4 text-[#EBDED4]/60 text-xs">
            <button 
              onClick={() => setIsGitHubModalOpen(true)}
              className="text-[#D9AA90] hover:text-[#EBDED4] hover:underline flex items-center gap-1 font-medium transition-colors"
            >
              <span className="text-[#A65E46]">📦</span> GitHub 打包发布
            </button>
            <button 
              onClick={() => setIsCloudLibraryOpen(true)}
              className="text-[#D9AA90] hover:text-[#EBDED4] hover:underline flex items-center gap-1 font-medium transition-colors"
            >
              <Database size={12} className="text-[#A65E46]" /> Cloud Saved Library
            </button>
            <a href="#" className="hover:text-[#D9AA90] transition-colors">Privacy</a>
            <a href="#" className="hover:text-[#D9AA90] transition-colors">Terms</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
